---
version: '3.8'
services:
  db:
    image: postgres:15.3-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD: PHONEBOOK_PASSWORD
      POSTGRES_USER: PHONEBOOK_USER
      POSTGRES_DB: PHONEBOOK_DB
    ports:
      - 5432:5432
