global:
  storageClass: "remote-disk"

auth:
  database: phone_book

primary:
  persistence:
    enabled: true
    size: 2Gi

readReplicas:
  replicaCount: 1
  persistence:
    enabled: true
    size: 2Gi
