---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phone-book.fullname" . }}
  labels:
    {{- include "phone-book.labels" . | nindent 4 }}
data:
  config.yaml: | {{- .Values.config | toYaml | nindent 4 }}
